export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const TOGGLE_ITEM_PURCHASE = 'TOGGLE_ITEM_PURCHASE';
export const UPDATE_FILTER_TEXT = 'UPDATE_FILTER_TEXT';
export const EMPTY_BASKET = 'EMPTY_BASKET';